name: Add Date to Markdown File

on:
  push:
    paths:
      - '**.md' # Срабатывание при загрузке файлов с расширением .md

jobs:
  addDate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add date to Markdown files
        run: |
          for file in $(find . -type f -name 'src/posts/*.md'); do
            echo "$(date)" >> $file
          done

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Add date to Markdown files"
          git push
