name: Add date to MD file

on:
  push:
    paths:
      - '**.md'

jobs:
  add-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          DATE=$(date +"%Y-%m-%d")
          for FILE in src/posts/*.md; do
            sed -i "s/date: .*/date: $DATE/" "$FILE"
          done
